// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // return web;
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // return ios;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        // return macos;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyCKKErbLvzCiveFAUQheLvMdCFWX3BoHPc',
  //   appId: '1:425846956945:web:60a7387ef3e0eeb786f030',
  //   messagingSenderId: '425846956945',
  //   projectId: 'software1-bb60d',
  //   authDomain: 'software1-bb60d.firebaseapp.com',
  //   storageBucket: 'software1-bb60d.appspot.com',
  //   measurementId: 'G-MLJNEY9MJR',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPQigUNcuOhmkMZ2Wsn9IjJMdt14L8l0',
    appId: '1:519384847887:android:cff34c366dc6ad0a66b57a',
    messagingSenderId: '519384847887',
    projectId: 'sw1-odoo-73ce6',
    storageBucket: 'sw1-odoo-73ce6.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCeulOIgJ8cwft7AutSK2m4UwycGgD_V20',
  //   appId: '1:425846956945:ios:1c840f7ddf1cb51e86f030',
  //   messagingSenderId: '425846956945',
  //   projectId: 'software1-bb60d',
  //   storageBucket: 'software1-bb60d.appspot.com',
  //   iosClientId:
  //       '425846956945-fq5aimp71h9ekcm817a5lqvmm7hkk0tr.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.exam1SoftwareMovil',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCeulOIgJ8cwft7AutSK2m4UwycGgD_V20',
  //   appId: '1:425846956945:ios:1c840f7ddf1cb51e86f030',
  //   messagingSenderId: '425846956945',
  //   projectId: 'software1-bb60d',
  //   storageBucket: 'software1-bb60d.appspot.com',
  //   iosClientId:
  //       '425846956945-fq5aimp71h9ekcm817a5lqvmm7hkk0tr.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.exam1SoftwareMovil',
  // );
}
